name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag hsonline:$(date +%s)
    - name: Build Docker image
      run: docker build -t Iamskyroot/tfg.

    - name: Push Docker image
      run: docker push Iamskyroot/tfg
